---
- name: EC2 nodes ({{state}})
  ec2:
    key_name: "{{elasticsearch_aws_key_name}}"
    group: "{{elasticsearch_ec2_group_name}}"
    instance_profile_name: "{{elasticsearch_iam_role_name}}"
    instance_type: "{{elasticsearch_ec2_instance_type}}"
    region: "{{aws_region}}"
    image: "{{elasticsearch_ec2_instance_image}}"
    wait: true
    exact_count: "{{elasticsearch_ec2_instance_count if state=='present' else 0}}"
    count_tag:
        Name: "{{elasticsearch_ec2_instance_tag}}"
    instance_tags:
      Name: "{{elasticsearch_ec2_instance_tag}}"
  register: elasticsearch_ec2_instances

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groupname=elasticsearch
  with_items: elasticsearch_ec2_instances.tagged_instances

- name: Wait for SSH to be available
  wait_for: host={{ item.public_ip }} port=22
  with_items: elasticsearch_ec2_instances.tagged_instances
