---
- name: Provision AWS CloudFormation stack ({{state}})
  cloudformation:
    stack_name: "{{ elasticsearch_name }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_elasticsearch.json
    template_parameters:
      KeyName: "{{ key_name }}"
      SSHCidrIp: "{{ user_cidr_ip }}"
      LoadBalancerName: "{{ elasticsearch_name }}"
      LoadBalancerSubnets: "{{ subnets | join(',') }}"
      GroupTag: "{{ elasticsearch_name }}"
      InstanceCount: "{{ elasticsearch_ec2_instance_count }}"
      InstanceType: "{{ elasticsearch_ec2_instance_type }}"
      InstanceImage: "{{ elasticsearch_ec2_instance_image }}"
  register: elasticsearch_stack
  tags:
    - elasticsearch

- name: Elasticsearch dev access security group rules ({{ dev_access_state }})
  cloudformation:
    stack_name: "{{ elasticsearch_name }}-dev-access"
    state: "{{ dev_access_state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_dev_access.json
    template_parameters:
      CidrIp: "{{ user_cidr_ip }}"
      FromPort: "{{ elasticsearch_port }}"
      ToPort: "{{ elasticsearch_port }}"
      SecurityGroup: "{{ elasticsearch_stack.stack_outputs.InstanceSecurityGroup }}"
  register: elasticsearch_dev_access_stack
  tags:
    - elasticsearch
    - dev-access
