---
- name: Provision AWS CloudFormation stack ({{state}})
  cloudformation:
    stack_name: "{{ elasticsearch_name }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_elasticsearch.json
    template_parameters:
      KeyName: "{{ keyname }}"
      GroupTag: "{{ elasticsearch_name }}"
      InstanceCount: "{{ elasticsearch_ec2_instance_count }}"
      InstanceType: "{{ elasticsearch_ec2_instance_type }}"
      InstanceImage: "{{ elasticsearch_ec2_instance_image }}"
  register: elasticsearch_stack
