---
- name: IAM role ({{state}})
  iam_role:
    name: "{{elasticsearch_iam_role_name}}"
    region: "{{aws_region}}"
    state: "{{state}}"
    policies:
      - name: ec2discovery
        allow_actions:
          - ec2:DescribeInstances

- name: AWS security group ({{state}})
  ec2_group:
    name: "{{elasticsearch_ec2_group_name}}"
    description: Elasticsearch cluster
    region: "{{aws_region}}"
    state: "{{state}}"
    rules:
      - proto: all
        group_name: "{{elasticsearch_ec2_group_name}}"
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 80.194.77.0/24
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 80.194.77.0/24
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
