language: python
python:
  - "3.6.3"
pip:
  - "9.0.1"
env:
  - TERRAFORM_VERSION=0.11.7 TERRAFORM_FILE_NAME=terraform_${TERRAFORM_VERSION}_linux_amd64.zip TERRAFORM_DOWNLOAD_URL=https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TERRAFORM_FILE_NAME}
install:
  - wget ${TERRAFORM_DOWNLOAD_URL}
  - unzip -o ${TERRAFORM_FILE_NAME} -d /tmp
  - export PATH=/tmp:${PATH}
  - pip install --no-use-wheel -r requirements-dev.txt
script:
  - make terraformatest
  - make test
notifications:
  email: false
