---
aws_region: eu-west-1

stage_name_short: "{{ stage_name[:3] }}"

name_suffix: "{{ stage_name }}-{{ environment_name }}"
name_suffix_short: "{{ stage_name_short }}-{{ environment_name }}"

elasticsearch_name: elasticsearch-{{ name_suffix }}
