{
 "title": "DM Apps",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "space", "label": "Environment", "query": "production,staging,preview" },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(cpu{organisation=\"digitalmarketplace\", app!~\"__conduit_.*__\"}, app)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\", space=\"$space\"}[60s]))",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Slow requests count (>2.5s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\" ,space=\"$space\", le=\"5\"}[60s])) -\nsum (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\" ,space=\"$space\", le=\"2.5\"}[60s]))\n",
     "legendFormat": "2.5-5s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"10\"}[60s])) -\nsum (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"5\"}[60s]))",
     "legendFormat": "5-10s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"+Inf\"}[60s])) -\nsum (increase(response_time_bucket{app=\"$app\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"10\"}[60s]))",
     "legendFormat": "10+"
    }
   ]
  },
  {
   "title": "5xx response count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (increase(requests{app=\"$app\", organisation=\"digitalmarketplace\" ,space=\"$space\", status_range=\"5xx\"}[60s]))",
     "legendFormat": "$app"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpu{organisation=\"digitalmarketplace\", space=\"$space\", app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 2, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(memory_bytes{organisation=\"digitalmarketplace\", space=\"$space\", app=\"$app\"}) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(cpu{organisation=\"digitalmarketplace\", space=\"$space\", app=\"$app\"}) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(disk_bytes{organisation=\"digitalmarketplace\", space=\"$space\", app=\"$app\"}) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Crashes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(crash{organisation=\"digitalmarketplace\", space=\"$space\", app=\"$app\"}[$__range]))"
    }
   ]
  }
 ]
}