{
 "title": "DM Database",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "space", "label": "Environment", "query": "production,staging,preview" }
  ]
 },
 "panels": [
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(commits{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(deadlocks{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(rollbacks{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "max(max_tx_age_s{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"})",
     "legendFormat": "Max transaction age"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(blocks_read{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Block reads"
    },
    {
     "expr": "sum(rate(blocks_hit{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Block cache hits"
    },
    {
     "expr": "sum(rate(idx_scan{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Index scans"
    },
    {
     "expr": "sum(rate(seq_scan{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"}[2m]))",
     "legendFormat": "Seq scans"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(connections{service=\"digitalmarketplace_api_db\",organisation=\"digitalmarketplace\",space=\"$space\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(blocked_connections{service=\"digitalmarketplace_api_db\",organisation=\"digitalmarketplace\",space=\"$space\"})",
     "legendFormat": "Blocked connections"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(write_iops{organisation=\"digitalmarketplace\", service=\"digitalmarketplace_api_db\", space=\"$space\"})",
     "legendFormat": "Write IOps"
    },
    {
     "expr": "sum(read_iops{organisation=\"digitalmarketplace\", service=\"digitalmarketplace_api_db\", space=\"$space\"})",
     "legendFormat": "Read IOps"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(cpu_credit_balance{organisation=\"digitalmarketplace\", space=\"$space\"})",
     "legendFormat": "CPU credit balance"
    },
    {
     "expr": "avg(cpu_percent{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"})",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dbsize_byte{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"})",
     "legendFormat": "Database size"
    },
    {
     "expr": "sum(freeable_memory_bytes{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"})",
     "legendFormat": "Freeable memory"
    },
    {
     "expr": "sum(swap_usage_bytes{organisation=\"digitalmarketplace\", space=\"$space\", service=\"digitalmarketplace_api_db\"})",
     "legendFormat": "Swap usage"
    }
   ]
  }
 ]
}