{
 "title": "DM Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "space", "label": "Environment", "query": "production,staging,preview" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request counts grouped by time - $space router",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\", space=\"$space\"}[60s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request counts grouped by time - $space api",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\", space=\"$space\"}[60s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Bad requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\" ,space=\"$space\", le=\"5\"}[60s])) -\nsum (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\" ,space=\"$space\", le=\"2.5\"}[60s]))\n",
     "legendFormat": "router 2.5-5 s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"10\"}[60s])) -\nsum (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"5\"}[60s]))",
     "legendFormat": "router 5-10 s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"+Inf\"}[60s])) -\nsum (increase(response_time_bucket{app=\"router\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"10\"}[60s]))",
     "legendFormat": "router 10+ s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\" ,space=\"$space\", le=\"5\"}[60s])) -\nsum (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\" ,space=\"$space\", le=\"2.5\"}[60s]))\n",
     "legendFormat": "api 2.5-5 s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"10\"}[60s])) -\nsum (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"5\"}[60s]))",
     "legendFormat": "api 5-10 s"
    },
    {
     "expr": "sum (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"+Inf\"}[60s])) -\nsum (increase(response_time_bucket{app=\"api\", organisation=\"digitalmarketplace\",status_range=\"2xx\",space=\"$space\", le=\"10\"}[60s]))",
     "legendFormat": "api 10+s"
    },
    {
     "expr": "sum (increase(requests{app=\"router\", organisation=\"digitalmarketplace\" ,space=\"$space\", status_range=\"5xx\"}[60s]))",
     "legendFormat": "router 5xx"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory usage per app - $space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(memory_bytes{organisation=\"digitalmarketplace\",space=\"$space\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Crashes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(crash{organisation=\"digitalmarketplace\", space=\"$space\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CPU usage per app - $space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{organisation=\"digitalmarketplace\",space=\"$space\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Conduits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cpu{org=\"digitalmarketplace\", space=\"$space\", app=~\".*conduit.*\"}) or vector(0)"
    }
   ]
  },
  { "title": "SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "% Non-500s",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(requests{organisation=\"digitalmarketplace\", app=\"router\", space=\"$space\", status_range=~\"2xx|3xx|4xx\"}) /\nsum(requests{organisation=\"digitalmarketplace\", app=\"router\", space=\"$space\"})"
    },
    {}
   ]
  },
  {
   "title": "% served under 1 second",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(response_time_bucket{organisation=\"digitalmarketplace\", space=\"$space\", app=\"router\", le=\"1\"}) /\nsum(requests{organisation=\"digitalmarketplace\", space=\"$space\", app=\"router\"})"
    },
    {}
   ]
  }
 ]
}