---
domain: "digitalmarketplace.service.gov.uk"
maintenance_mode: maintenance
instances: 5

router:
  # If you change the number of router instances, update the per-instance rate limit to keep the overall rate limit the
  # same. See digitalmarketplace-router/templates/nginx.conf.j2#L53
  instances: 6
  rate_limiting_enabled: enabled
  routes:
    - www.digitalmarketplace.service.gov.uk
    - api.digitalmarketplace.service.gov.uk
    - search-api.digitalmarketplace.service.gov.uk
    - antivirus-api.digitalmarketplace.service.gov.uk
    - assets.digitalmarketplace.service.gov.uk

api:
  memory: 2GB
  instances: 10

user-frontend:
  instances: 2

admin-frontend:
  instances: 2
  memory: 1GB

antivirus-api:
  instances: 4

buyer-frontend:
  memory: 1G

search-api:
  memory: 1G

supplier-frontend:
  instances: 10
  memory: 1GB
