---
domain: "digitalmarketplace.service.gov.uk"
maintenance_mode: live
instances: 5

router:
  instances: 3
  routes:
    - www.digitalmarketplace.service.gov.uk
    - api.digitalmarketplace.service.gov.uk
    - search-api.digitalmarketplace.service.gov.uk
    - assets.digitalmarketplace.service.gov.uk

api:
  memory: 2GB
  instances: 15

user-frontend:
  instances: 2

admin-frontend:
  instances: 2

supplier-frontend:
  memory: 750MB
  instances: 15
