---
domain: "digitalmarketplace.service.gov.uk"
maintenance_mode: live
instances: 5

router:
  instances: 6
  rate_limiting_enabled: enabled
  routes:
    - dm-router-{env}.cloudapps.digital
    - dm-router-{env}.cloudapps.digital/_metrics
    - www.digitalmarketplace.service.gov.uk
    - api.digitalmarketplace.service.gov.uk
    - search-api.digitalmarketplace.service.gov.uk
    - antivirus-api.digitalmarketplace.service.gov.uk
    - assets.digitalmarketplace.service.gov.uk

api:
  memory: 2GB
  instances: 30

user-frontend:
  instances: 2

admin-frontend:
  instances: 2
  memory: 1GB

antivirus-api:
  instances: 4

buyer-frontend:
  instances: 10
  memory: 1G

search-api:
  instances: 8
  memory: 1G

supplier-frontend:
  instances: 40
  memory: 4GB
