---
domain: "digitalmarketplace.service.gov.uk"
maintenance_mode: live
instances: 5

router:
  instances: 3
  rate_limiting_enabled: enabled
  routes:
    - www.digitalmarketplace.service.gov.uk
    - api.digitalmarketplace.service.gov.uk
    - search-api.digitalmarketplace.service.gov.uk
    - antivirus-api.digitalmarketplace.service.gov.uk
    - assets.digitalmarketplace.service.gov.uk

api:
  memory: 2GB

user-frontend:
  instances: 2

admin-frontend:
  instances: 2

antivirus-api:
  instances: 2
