---
root_domain: "beta.digitalmarketplace.service.gov.uk"
ssl_certificate_id: "arn:aws:iam::050019655025:server-certificate/star-beta-2016-05-05"
iam_certificate_id: "ASCAJGSVATSZD7C6QICNM"
subnets:
  - subnet-9a9713ed
  - subnet-63b1683a
  - subnet-ad0894c8
