---
domain: staging.marketplace.team
maintenance_mode: live
instances: 2

api:
  memory: 2GB
  services:
    - digitalmarketplace_api_db-restored-2
    - digitalmarketplace_prometheus
    - digitalmarketplace_splunk

router:
  instances: 3
  rate_limiting_enabled: enabled
