---
root_domain: "digitalmarketplace.service.gov.uk"
ssl_certificate_id: "arn:aws:acm:eu-west-1:050019655025:certificate/a0eb63fa-fdf8-4598-bae5-17d082966e0b"

monitoring:
  email: "support+production-staging@digitalmarketplace.service.gov.uk"

database:
  multi_az: "true"
  backup_retention_period: "1"
  slow_query_log_duration_ms: -1
  snapshot_id: "staging-2016-12-20t1037"

vpc_id: vpc-70319115
subnets:
  - subnet-9a9713ed
  - subnet-63b1683a
  - subnet-ad0894c8
