---
root_domain: "beta.digitalmarketplace.service.gov.uk"
ssl_certificate_id: "arn:aws:iam::050019655025:server-certificate/star-beta-2016-05-05"
iam_certificate_id: "ASCAJGSVATSZD7C6QICNM"

monitoring:
  email: support@digitalmarketplace.service.gov.uk

database:
  multi_az: "true"
  backup_retention_period: "1"
  snapshot_id: "stage-2015-05-13t1454"

vpc_id: vpc-70319115
subnets:
  - subnet-9a9713ed
  - subnet-63b1683a
  - subnet-ad0894c8
