---
root_domain: "digitalmarketplace.service.gov.uk"
ssl_certificate_id: "arn:aws:iam::050019655025:server-certificate/star-digitalmarketplace-2016-05-13"
iam_certificate_id: "ASCAJG65ZXOA7JBRVORN6"

monitoring:
  email: "support+production-staging@digitalmarketplace.service.gov.uk"

database:
  multi_az: "true"
  backup_retention_period: "1"
  slow_query_log_duration_ms: -1
  snapshot_id: "staging-2015-07-17t1003"

vpc_id: vpc-70319115
subnets:
  - subnet-9a9713ed
  - subnet-63b1683a
  - subnet-ad0894c8
