---
domain: staging.marketplace.team
maintenance_mode: live
instances: 2

api:
  memory: 2GB

router:
  rate_limiting_enabled: disabled

buyer-frontend:
  services:
    - digitalmarketplace_prometheus 
    - digitalmarketplace_splunk
    - digitalmarketplace_redis

admin-frontend:
  services:
    - digitalmarketplace_prometheus 
    - digitalmarketplace_splunk
    - digitalmarketplace_redis

brief-responses-frontend:
  services:
    - digitalmarketplace_prometheus 
    - digitalmarketplace_splunk
    - digitalmarketplace_redis

briefs-frontend:
  services:
    - digitalmarketplace_prometheus 
    - digitalmarketplace_splunk
    - digitalmarketplace_redis

supplier-frontend:
  services:
    - digitalmarketplace_prometheus 
    - digitalmarketplace_splunk
    - digitalmarketplace_redis
    
user-frontend:
  services:
    - digitalmarketplace_prometheus 
    - digitalmarketplace_splunk
    - digitalmarketplace_redis

