---
- name: Digital Marketplace API Elastic Beanstalk app ({{state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ stage_name }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_elasticbeanstalk_app.json
    template_parameters:
      ApplicationName: "{{ digitalmarketplace_api_app_name }}"
  register: digitalmarketplace_api_app_stack
  tags:
    - digitalmarketplace-api
    - base

- name: Digital Marketplace API Elastic Beanstalk env ({{state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ name_suffix }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_digitalmarketplace_api.json
    template_parameters:
      ApplicationName: "{{ digitalmarketplace_api_app_name }}"
      EnvironmentName: "{{ digitalmarketplace_api_env_name }}"
      KeyName: "{{ key_name }}"
      APIAuthTokens: "{{ digitalmarketplace_api_auth_tokens | join(':') }}"
      DBName: "{{ digitalmarketplace_api_db_name }}"
      DBUser: "{{ digitalmarketplace_api_db_user }}"
      DBPassword: "{{ digitalmarketplace_api_db_password }}"
      DBInstanceType: "{{ digitalmarketplace_api_db_instance_type }}"
      DBAllocatedStorage: "{{ digitalmarketplace_api_db_allocated_storage }}"
  register: digitalmarketplace_api_env_stack
  tags:
    - digitalmarketplace-api

- name: RDS dev access security group rules ({{dev_access_state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ name_suffix }}-dev-access"
    state: "{{ dev_access_state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_dev_access.json
    template_parameters:
      CidrIp: "{{ user_cidr_ip }}"
      FromPort: "{{ digitalmarketplace_api_rds_port }}"
      ToPort: "{{ digitalmarketplace_api_rds_port }}"
      SecurityGroup: "{{ digitalmarketplace_api_env_stack.stack_outputs.RDSSecurityGroup }}"
  register: digitalmarketplace_api_rds_dev_access_stack
  tags:
    - digitalmarketplace-api
    - dev-access
