---
- name: Digital Marketplace API Elastic Beanstalk app ({{state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ environment_name }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_digitalmarketplace_api_app.json
    template_parameters:
      ApplicationName: "digitalmarketplace-api"
  register: digitalmarketplace_api_app_stack
  tags:
    - digitalmarketplace-api
    - base

- name: Digital Marketplace API Elastic Beanstalk env ({{state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ name_suffix }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_digitalmarketplace_api_env.json
    template_parameters:
      ApplicationName: "digitalmarketplace-api"
      EnvironmentName: "dmapi-{{ name_suffix_short }}"
      DBName: "digitalmarketplace_{{ name_suffix | replace('-', '_') }}"
      DBUser: "digitalmarketplace"
      DBPassword: "{{ dmapi_db_password }}"
      DBInstanceType: "{{ dmapi_db_instance_type }}"
      DBAllocatedStorage: "{{ dmapi_db_allocated_storage }}"
  register: digitalmarketplace_api_env_stack
  tags:
    - digitalmarketplace-api
