---
- name: Digital Marketplace API Elastic Beanstalk app ({{state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ stage_name }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_digitalmarketplace_api_app.json
    template_parameters:
      ApplicationName: "{{ digitalmarketplace_api_app_name }}"
  register: digitalmarketplace_api_app_stack
  tags:
    - digitalmarketplace-api
    - base

- name: Digital Marketplace API Elastic Beanstalk env ({{state}})
  cloudformation:
    stack_name: "digitalmarketplace-api-{{ name_suffix }}"
    state: "{{ state }}"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: ../cloudformation_templates/aws_digitalmarketplace_api_env.json
    template_parameters:
      ApplicationName: "{{ digitalmarketplace_api_app_name }}"
      EnvironmentName: "{{ digitalmarketplace_api_env_name }}"
      KeyName: "{{ key_name }}"
      DBName: "{{ digitalmarketplace_api_db_name }}"
      DBUser: "{{ digitalmarketplace_api_db_user }}"
      DBPassword: "{{ digitalmarketplace_api_db_password }}"
      DBInstanceType: "{{ digitalmarketplace_api_db_instance_type }}"
      DBAllocatedStorage: "{{ digitalmarketplace_api_db_allocated_storage }}"
  register: digitalmarketplace_api_env_stack
  tags:
    - digitalmarketplace-api
