---
- hosts: localhost
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  roles:
    - role: elasticsearch
      tags: elasticsearch
    - role: cloudwatch
      tags: cloudwatch
      config_name: elasticsearch
