---
- hosts: localhost
  name: setup
  user: ubuntu
  sudo: True

  roles:
    - role: common
      tags: common
    - role: nginx
      tags: nginx
    - role: cloudwatch
      tags: cloudwatch
      config_name: nginx
