---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
      - role: aws_elasticsearch
        elasticsearch_aws_key_name: "{{ lookup('env', 'AWS_KEY_NAME') }}"
        state: present

- hosts: elasticsearch
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  roles:
    - elasticsearch

