---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/common.yml
    - vars/{{ environment }}.yml

  roles:
    - role: aws_elasticsearch
      elasticsearch_aws_key_name: "{{ keyname }}"
      state: present

- hosts: elasticsearch
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  vars_files:
    - vars/common.yml
    - vars/{{ environment }}.yml

  roles:
    - elasticsearch

