---
- hosts: tag_Group_elasticsearch-{{ stage }}-{{ environment }}
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  roles:
    - role: elasticsearch
      tags: elasticsearch
      elasticsearch_name: elasticsearch-{{ stage }}-{{ environment }}

- hosts: tag_Group_nginx-{{ stage }}-{{ environment }}
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  roles:
    - role: nginx
      tags: nginx
      nginx_domain: "{{ stage }}{% if stage != environment %}-{{ environment }}{% endif %}.{{ root_domain }}"
      buyer_frontend_url: "https://{{ stage }}{% if stage != environment %}-{{ environment }}{% endif %}-buyer-frontend.{{ root_domain }}"
      admin_frontend_url: "https://{{ stage }}{% if stage != environment %}-{{ environment }}{% endif %}-admin-frontend.{{ root_domain }}"
      supplier_frontend_url: "https://{{ stage }}{% if stage != environment %}-{{ environment }}{% endif %}-supplier-frontend.{{ root_domain }}"
