---
- hosts: tag_Group_elasticsearch-{{ stage }}-{{ environment }}
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  roles:
    - role: elasticsearch
      tags: elasticsearch
      elasticsearch_name: elasticsearch-{{ stage }}-{{ environment }}
