---
- hosts: tag_Group_{{ elasticsearch_name }}
  name: setup
  user: ubuntu
  gather_facts: True
  sudo: True

  vars_files:
    - vars/common.yml
    - vars/{{ stage_name }}.yml

  roles:
    - role: elasticsearch
      tags: elasticsearch
