---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/common.yml
    - vars/{{ stage_name }}.yml

  roles:
    - role: aws_elasticsearch
      state: present

    - role: aws_digitalmarketplace_api
      state: present
