---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/common.yml
    - vars/{{ environment_name }}.yml

  roles:
    - role: aws_elasticsearch
      state: absent
